
// Common or dashboard
export const SET_IS_LOADING = "SET_IS_LOADING";
export const SET_IS_SIDEBAR_OPEN = 'SET_IS_SIDEBAR_OPEN';

//Review
export const GET_ASTROLOGERS_REVIEWS = "GET_ASTROLOGERS_REVIEWS";
export const SET_ASTROLOGERS_REVIEWS = "SET_ASTROLOGERS_REVIEWS";
export const GET_APP_REVIEWS = "GET_APP_REVIEWS";
export const SET_APP_REVIEWS = "SET_APP_REVIEWS";
export const UPDATE_ASTROLOER_REVIEW_STATUS = 'UPDATE_ASTROLOER_REVIEW_STATUS';
export const DELETE_ASTROLOGER_REVIEW = 'DELETE_ASTROLOGER_REVIEW'

//Customer
export const GET_ALL_CUSTOMER = 'GET_ALL_CUSTOMER';
export const SET_ALL_CUSTOMER = 'SET_ALL_CUSTOMER';
export const DELETE_CUSTOMER = 'DELETE_CUSTOMER';
export const BAN_CUSTOMER = 'BAN_CUSTOMER'
export const UPDATE_CUSTOMER = 'UPDATE_CUSTOMER'

//Astrologer
export const GET_ALL_ASTROLOGER = 'GET_ALL_ASTROLOGER';
export const SET_ALL_ASTROLOGER = 'SET_ALL_ASTROLOGER';
export const UPDATE_ASTROLOGER_CHAT_STATUS = 'UPDATE_ASTROLOGER_CHAT_STATUS';
export const UPDATE_ASTROLOER_CALL_STATUS = 'UPDATE_ASTROLOER_CALL_STATUS'
export const GET_ENQUIRY_ASTROLOGERS = 'GET_ENQUIRY_ASTROLOGERS';
export const SET_ENQUIRY_ASTROLOGERS = 'SET_ENQUIRY_ASTROLOGERS';
export const UPDATE_ENQUIRY_STATUS = 'UPDATE_ENQUIRY_STATUS';
export const UPDATE_ASTROLOGER_DATA = 'UPDATE_ASTROLOGER_DATA'
export const ADD_ASTROLOGER = 'ADD_ASTROLOGER'
export const VERIFY_UNVERIFY_ASTROLOGER = 'VERIFY_UNVERIFY_ASTROLOGER';
export const DELETE_ASTROLOGER = 'DELETE_ASTROLOGER'

//Experties
export const GET_ALL_EXPERTIES = 'GET_ALL_EXPERTIES';
export const GET_ALL_MAIN_EXPERTIES = 'GET_ALL_MAIN_EXPERTIES';
export const SET_ALL_EXPERTIES = 'SET_ALL_EXPERTIES';
export const SET_ALL_MAIN_EXPERTIES = 'SET_ALL_MAIN_EXPERTIES'
export const CREATE_EXPERTIES = 'CREATE_EXPERTIES'
export const CREATE_MAIN_EXPERTIES = 'CREATE_MAIN_EXPERTIES'
export const UPDATE_EXPERTIES = 'UPDATE_EXPERTIES';
export const UPDATE_MAIN_EXPERTIES = 'UPDATE_MAIN_EXPERTIES'
export const DELETE_EXPERTIES = 'DELETE_EXPERTIES'
export const DELETE_MAIN_EXPERTIES = 'DELETE_MAIN_EXPERTIES'

//Skills 
export const CREATE_SKILL = 'CREATE_SKILL';
export const GET_ALL_SKILLS = 'GET_ALL_SKILLS'
export const SET_ALL_SKILLS = 'SET_ALL_SKILLS';
export const UPDATE_SKILL = 'UPDATE_SKILL'
export const DELETE_SKILL = 'DELETE_SKILL'

export const CREATE_SUB_SKILL = 'CREATE_SUB_SKILL';
export const GET_ALL_SUB_SKILLS = 'GET_ALL_SUB_SKILLS'
export const SET_ALL_SUB_SKILLS = 'SET_ALL_SUB_SKILLS';
export const UPDATE_SUB_SKILL = 'UPDATE_SUB_SKILL'
export const DELETE_SUB_SKILL = 'DELETE_SUB_SKILL'

//Remedies 
export const CREATE_REMEDY = 'CREATE_REMEDY'
export const GET_ALL_REMEDIES = 'GET_ALL_REMEDIES'
export const SET_ALL_REMEDIES = 'SET_ALL_REMEDIES'
export const UPDATE_REMEDY = 'UPDATE_REMEDY'
export const DELETE_REMEDY = 'DELETE_REMEDY'

//Banners
export const UPLOAD_APP_BANNER = 'UPLOAD_APP_BANNER'
export const UPLOAD_WEB_BANNER = 'UPLOAD_WEB_BANNER'
export const GET_APP_BANNERS = 'GET_APP_BANNERS'
export const SET_APP_BANNERS = 'SET_APP_BANNERS'
export const DELETE_BANNERS = 'DELETE_BANNERS'
export const EDIT_BANNERS = 'EDIT_BANNERS'

//Notification 
export const GET_CUSTOMER_NOTIFICATIONS = 'GET_CUSTOMER_NOTIFICATIONS'
export const GET_ASTROLOGER_NOTIFICATIONS = 'GET_ASTROLOGER_NOTIFICATIONS'
export const SET_CUSTOMER_NOTIFICATIONS = 'GET_CUSTOMER_NOTIFICATIONS'
export const SET_ASTROLOGER_NOTIFICATIONS = 'GET_ASTROLOGER_NOTIFICATIONS'
export const SEND_CUSTOMER_NOTIFICATIONS = 'SEND_CUSTOMER_NOTIFICATIONS'
export const SEND_ASTROLOGER_NOTIFICATIONS = 'SEND_ASTROLOGER_NOTIFICATIONS'
export const DELETE_CUSTOMER_NOTIFICATIONS = 'GET_CUSTOMER_NOTIFICATIONS'
export const DELETE_ASTROLOGER_NOTIFICATIONS = 'GET_ASTROLOGER_NOTIFICATIONS'

//History
export const GET_CHAT_HISTORY = 'GET_CHAT_HISTORY';
export const SET_CHAT_HISTORY = 'SET_CHAT_HISTORY';
export const GET_CHAT_SUMMARY = 'GET_CHAT_SUMMARY';
export const SET_CHAT_SUMMARY = 'SET_CHAT_SUMMARY';
export const GET_CALL_HISTORY = 'GET_CALL_HISTORY';
export const SET_CALL_HISTORY = 'SET_CALL_HISTORY';

//Dashboard
export const GET_DASHBOARD = 'GET_DASHBOARD'
export const SET_DASHBOARD = 'SET_DASHBOARD'

//Reports
export const GET_ADMIN_EARNINGS = 'GET_ADMIN_EARNINGS'
export const SET_ADMIN_EARNINGS = 'SET_ADMIN_EARNINGS'




